openvpn_users_ipv4_base: 10.1.0.0
openvpn_users_ipv4_netmask: 255.255.0.0
openvpn_users_ipv4_server: 10.1.0.1

# manche Server moechten zusaetzliche IPs announcieren - alle anderen brauchen keine extra-Einstellungen
# Sobald wir IPv6 unterstuetzen, brauchen wir diese Einstellungen.
ugw_openvpn_users_extra_settings: ""

openvpn_users_cert_file: /etc/ssl/private/opennet-initiative.de/{{ short_hostname }}.opennet-initiative.de.crt
openvpn_users_key_file: /etc/ssl/private/opennet-initiative.de/{{ short_hostname }}.opennet-initiative.de.key
# TODO: vor dem Umstieg muessen die UGW-CA-Zertifikate aktualisiert werden
#openvpn_ugw_cert_file: /etc/ssl/private/opennet-initiative.de/{{ short_hostname }}.opennet-initiative.de.crt
#openvpn_ugw_key_file: /etc/ssl/private/opennet-initiative.de/{{ short_hostname }}.opennet-initiative.de.key
openvpn_ugw_cert_file: /etc/openvpn/opennet_ugw/server.crt
openvpn_ugw_key_file: /etc/openvpn/opennet_ugw/server.key

ugw_server_crl_list:
  - { name: "Nutzer-Tunnel", minute: "48", crl: "opennet-vpn-user.crl", ca_cert: "/etc/openvpn/opennet_users/ca.crt" }
  - { name: "UGW-Tunnel", minute: "49", crl: "opennet-vpn-ugw.crl", ca_cert: "/etc/openvpn/opennet_ugw/ca.crt" }

# Oeffentliche IP-Adressen von Hosts, die auch im Mesh erreichbar sein sollen
ugw_external_forward_allow_ipv4:
  # downloads.openwrt.org: Paketinstallation fuer APs
  - 78.24.191.177
  # developer.mapquest.com: Mapquest-Logo der alten Karte (on-i.de/map)
  - 23.253.11.253
  # otile1.mqcdn.com: Standard-Hintergrund der alten Karte (on-i.de/map)
  - 92.197.129.10
  - 92.197.129.25
  # www.geodaten-mv.de: Luftbilder als Hintergrund der alten Karte (on-i.de/map)
  - 195.145.109.67
  # a.tile.openstreetmap.org: Hintergrund-Tiles fuer OSM-Layer der alten Karte (on-i.de/map)
  - 81.7.11.83
  - 144.76.70.77

openvpn_ugw_interface: tap-mesh
openvpn_users_interface: tun-users

olsr_nameservice_announcements:
  - "dns://{{ olsr_main_ip }}:53|udp|dns"
  - "ntp://{{ olsr_main_ip }}:123|udp|ntp"
  - "openvpn://{{ olsr_main_ip }}:1600|udp|gw"

# das "olsr_main_ip"-Announcement ist fuer APs mit alter Firmware (z.B. 0.9on5) notwendig
olsr_hna_announcements_ipv4: "{{ [olsr_main_ip]|union(ugw_external_forward_allow_ipv4) }}"

non_olsr_interfaces:
  - "{{ wan_interface }}"
  - "{{ openvpn_users_interface }}"
