openvpn_users_ipv4_base: 10.1.0.0
openvpn_users_ipv4_netmask: 255.255.0.0
openvpn_users_ipv4_server: 10.1.0.1

# manche Server moechten zusaetzliche IPs announcieren - alle anderen brauchen keine extra-Einstellungen
ugw_openvpn_users_extra_settings: ""

openvpn_users_cert_file: /etc/ssl/private/opennet-initiative.de/{{ short_hostname }}.opennet-initiative.de.crt
openvpn_users_key_file: /etc/ssl/private/opennet-initiative.de/{{ short_hostname }}.opennet-initiative.de.key
# TODO: vor dem Umstieg muessen die UGW-CA-Zertifikate aktualisiert werden
#openvpn_ugw_cert_file: /etc/ssl/private/opennet-initiative.de/{{ short_hostname }}.opennet-initiative.de.crt
#openvpn_ugw_key_file: /etc/ssl/private/opennet-initiative.de/{{ short_hostname }}.opennet-initiative.de.key
openvpn_ugw_cert_file: /etc/openvpn/opennet_ugw/server.crt
openvpn_ugw_key_file: /etc/openvpn/opennet_ugw/server.key

ugw_server_crl_list:
  - { name: "Nutzer-Tunnel", minute: "48", crl: "opennet-vpn-user.crl", ca_cert: "/etc/openvpn/opennet_users/ca.crt" }
  - { name: "UGW-Tunnel", minute: "49", crl: "opennet-vpn-ugw.crl", ca_cert: "/etc/openvpn/opennet_ugw/ca.crt" }
