# manche Server moechten zusaetzliche IPs announcieren - alle anderen brauchen keine extra-Einstellungen
ugw_openvpn_users_extra_settings: ""

openvpn_users_cert_file: /etc/ssl/private/opennet-initiative.de/{{ short_hostname }}.opennet-initiative.de.crt
openvpn_users_key_file: /etc/ssl/private/opennet-initiative.de/{{ short_hostname }}.opennet-initiative.de.key
# TODO: pruefen, ob wir anstelle der alten UGW-VPN-Zertifikate nun ebenfalls die obigen verwenden koennen
openvpn_ugw_cert_file: /etc/openvpn/opennet_ugw/server.crt
openvpn_ugw_key_file: /etc/openvpn/opennet_ugw/server.key

dns_zone_masters:
  - 139.30.241.202
  - 192.168.10.2

