- name: install - SmokePing / Apache FCGI installieren
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - smokeping
    - libapache2-mod-fcgid
  notify: 
    - restart smokeping
    - restart apache2
