#
# Diese Rollen ist noch in Entwicklung und soll gewollt einfach gehalten werden.
# So können auch einfach Änderungen (z.B anderer VPN Server) vorgenommen werden.
#
# Es wird angenommen, dass die Rolle "ugw-server" bereits installiert ist.
# Ansonsten müssten große Teile davon übernommen werden.
#
- include: networking.yml
# Wir wollen erstmal ohne User-Port-Forward arbeiten. Somit wird erstmal ein
# Tunnel im Tunnel aufgebaut. Zum Testen reicht uns das erstmal.
#- include: user-port-forwards.yml

- include: ferm.yml
- include: openvpn.yml
- include: radvd.yml
- include: dhcpd6.yml

#TODO Monitoring
#- include: openvpn-status.yml
#- include: munin-openvpn.yml
#- include: web.yml
#- include: speed-tests.yml
