- name: Apt-Repo GPG Public Keys-Verzeichnis anlegen
  file: state=directory
        dest=/home/{{ apt_repo_user }}/{{ apt_md_dir }}/keys
        owner={{ apt_repo_user}}
        group={{ apt_repo_user}}

- name: Apt-Repo Bin-Verzeichnis anlegen
  file: state=directory
        dest=/home/{{ apt_repo_user }}/bin
        owner={{ apt_repo_user}}
        group={{ apt_repo_user}}

- name: Verschlüsselung - Crypto-Hinweis kopieren
  copy:
       src={{ apt_md_sign }}
       dest=/home/{{ apt_repo_user }}/{{ apt_md_sign }}

# FIXME: GPG Key anlegen fehlt
