- name: bind - Nameserver installieren
  apt: state=present pkg=bind9

- block:
  - name: bind - dnskey vom primaeren DNS-Server abholen
    delegate_to: root@{{ dns_zone_primary_with_dnskey }}
    shell: grep -w 'secret' /etc/bind/keys/opennet-transfer.key | cut -f 2 -d '"'
    register: dnskey_secret_fetch
    changed_when: False
    run_once: yes

  - fail: msg="Kein geheimer dnskey auf dem primaeren DNS-Server gefunden"
    when: not dnskey_secret_fetch.stdout

  - name: bind - Nameserver konfigurieren
    template:
      src=named.conf.local
      dest=/etc/bind/
    notify: restart bind

# ignoriere den "--check"-Modus (sonst schlagen die Schritt beim Testen fehl)
  when: not ansible_check_mode

- name: bind - originale Nameserver-Konfiguration deaktivieren
  lineinfile: state=present
              backrefs=yes
              dest=/etc/bind/named.conf
              regexp='^(include.*named\.conf\.options.*)$'
              line='#\1'
  notify: restart bind
