- name: munin - Plugin für Bind aktivieren
  file:
          state: link
          src: /usr/share/munin/plugins/bind9_rndc
          dest: /etc/munin/plugins/bind9_rndc
  notify: restart munin-node

- name: munin - Plugin für Bind konfigurieren
  copy:
          src: munin-plugin.conf
          dest: /etc/munin/plugin-conf.d/opennet_dns_slave
  notify: restart munin-node
