- hosts: frieda23:ae22:hetzner
  roles:
    - role: basic-server
    - role: olsr-node
    - role: letsencrypt
      when: letsencrypt_certificates is defined

- hosts: ryoko.on:aqua.on:jun.on
  roles:
    - virtualization-server
