- hosts: ae22:frieda23:hetzner
  roles:
    - basic-server
    - olsr
    - olsr2
    - role: letsencrypt
      when: letsencrypt_certificates is defined
    - role: apache2-server
      when: apache2_sites is defined

- hosts: gateway_server
  roles:
    - basic-server
    - olsr
    - olsr2
    - python-module
    - gateway-server
    - nameserver-secondary
    - role: letsencrypt
      when: letsencrypt_certificates is defined
    - role: apache2-server
      when: apache2_sites is defined

- hosts: ryoko.on:aqua.on:tamago.on:akito.on-i.de
  roles:
    - nameserver-resolver
    - virtualization-server

- hosts: jun.on
  roles:
    - domain-proxy
  tags: 
    - domain-proxy

- hosts: inez.on:maki.on
  roles:
    - backup-storage

- hosts: amano.on
  roles:
    - mitgliedsantrag
    - opennetca

- hosts: tenkawa.on
  roles:
    - media-mirror

- hosts: kinjo.on
  roles:
    - homematic

- hosts: goat.on
  roles:
    - buildbot-controller
  tags:
    - buildbot

- hosts: hoshino.on
  roles:
    - buildbot-worker
  tags:
    - buildbot

# wireguard-server in development
- hosts: kazama.on
  roles:
    - wireguard-server

# mediawiki in development
- hosts: hikaru.on
  roles:
    - mediawiki
    - www-server

# Service Discovery + Git Server TODO
- hosts: izumi.on
  roles:
    - service-discovery

# Layer2 User VPN with IPv6 in development
- hosts: gai.on-i.de
  roles:
    - ugw-server-ipv6

# Gluon+Babel Tests
- hosts: itsuki.on-i.de
  roles:
    - basic-server

# Mitgliederverwaltung Debian 10
- hosts: nagare.on
  roles:
    - mitgliederverwaltung
