- hosts: ae22:frieda23:hetzner
  roles:
    - role: basic-server
    - role: olsr-node
    - role: letsencrypt
      when: letsencrypt_certificates is defined

- hosts: ryoko.on:aqua.on:tamago.on
  roles:
    - local-dns-resolver
    - virtualization-server

- hosts: jun.on
  roles:
    - domain-proxy

- hosts: inez.on
  roles:
    - backup-storage
