- hosts: ae22:frieda23:hetzner
  roles:
    - role: basic-server
    - role: olsr-node
    - role: letsencrypt
      when: letsencrypt_certificates is defined
    - role: apache2-server
      when: apache2_sites is defined

- hosts: ryoko.on:aqua.on:tamago.on
  roles:
    - local-dns-resolver
    - virtualization-server

- hosts: jun.on
  roles:
    - domain-proxy

- hosts: inez.on:maki.on
  roles:
    - backup-storage

- hosts: amano.on
  roles:
    - mitgliederverwaltung-server
