- hosts: ae22:frieda23:hetzner
  roles:
    - role: basic-server
    - role: olsr
    - role: letsencrypt
      when: letsencrypt_certificates is defined
    - role: apache2-server
      when: apache2_sites is defined

- hosts: ryoko.on:aqua.on:tamago.on:akito.on-i.de
  roles:
    - nameserver-resolver
    - virtualization-server

- hosts: jun.on
  roles:
    - domain-proxy

- hosts: inez.on:maki.on
  roles:
    - backup-storage
    - olsr2

- hosts: amano.on
  roles:
    - mitgliederverwaltung
    - mitgliedsantrag
    - opennetca

- hosts: tenkawa.on
  roles:
    - media-mirror

- hosts: kinjo.on
  roles:
    - homematic

- hosts: goat.on
  roles:
    - buildbot-controller
  tags:
    - buildbot

- hosts: hoshino.on
  roles:
    - buildbot-worker
  tags:
    - buildbot

# wireguard-server in development
- hosts: kazama.on
  roles:
    - wireguard-server

# mediawiki in development
- hosts: hikaru.on
  roles:
    - mediawiki
    - www-server

# IRC Server disabled, Service Discovery + Git TODO
#- hosts: izumi.on
#  roles:
#    - irc-server

# Layer2 User VPN with IPv6 in development
- hosts: gai.on-i.de
  roles:
    - ugw-server-ipv6

# Gluon+Babel Tests
- hosts: itsuki.on-i.de
  roles:
    - basic-server
