- hosts: frieda23:ae22:hetzner
  roles:
    - role: basic-server
    - role: olsr-node
    - role: letsencrypt
      when: letsencrypt_certificates is defined

- hosts: ryoko.on:aqua.on:jun.on
  roles:
    - virtualization-server

# TODO: vorerst abgeschaltet (wegen Monitoring-Warnungen auf akito); Umzug zu aqua
# hosts: akito.on-i.de
# roles:
#   # TODO: die Rolle 'local-dns-resolver' auf alle Hosts uebertragen
#   - local-dns-resolver
#   - backup-storage
