- hosts: ae22:frieda23:hetzner
  roles:
    - role: basic-server
    - role: olsr-node
    - role: letsencrypt
      when: letsencrypt_certificates is defined

- hosts: ryoko.on:aqua.on:tamago.on:akito.on-i.de
  roles:
    - local-dns-resolver
    - virtualization-server

- hosts: jun.on
  roles:
    - domain-proxy

- hosts: inez.on:maki.on
  roles:
    - backup-storage

- hosts: amano.on
  roles:
    - mitgliederverwaltung-server
    - mitgliedsantrag-server

- hosts: tenkawa.on
  roles:
    - media-server

# apt-repository in development
- hosts: server-mathias.on
  roles:
    - apt-repository

# wireguard-server in development
- hosts: kazama.on
  roles:
    - wireguard-server

#apache2-server Rolle muss am Ende ausgeführt werden, weil sonst Fehlermeldungen
#wegen Fehlendem DocumentRoot auftreten
- hosts: izumi.on:tenkawa.on:amano.on:server-mathias.on:ruri.on
  roles:
    - apache2-server
