- name: munin - OSLR Plugin herunterladen
  get_url:
    url: "https://raw.githubusercontent.com/opennet-initiative/firmware/main/opennet/packages/on-monitoring/files/usr/share/munin-plugins-available/olsrd"
    dest: "/etc/munin/plugins/olsrd"
    force: yes
    mode: 0755
  # nicht im "check"-Modus ausfuehren (es gilt sonst immer als Änderung)
  when: not ansible_check_mode
  notify: restart munin-node
