buildbot_worker_path: "/var/lib/buildbot/workers/{{ buildbot_worker1_name }}"
buildbot_controller_host: "goat.on"
buildbot_home: "/var/lib/buildbot"  # home directory of buildbot user

# upload
buildbot_upload_server: "downloads.on"
buildbot_upload_user: "trac-bitten-slave"
