backup_storage_source_hosts:
  # Virtualization
  - akito.on-i.de
  - aqua.on
  - tamago.on
  - ryoko.on
  # Services
  - heartofgold.on
  - howmei.on
  - jun.on
  - on-v6.on-i.de
  - ruri.on
  - yurika.on
  - izumi.on
  - amano.on
  - crimson.on
  # TODO: bei Erreichbarkeit wieder anschalten
  #- haruka.on
  - tenkawa.on
  # Gateways
  - erina.on
  - megumi.on
  # TODO: bei Erreichbarkeit wieder anschalten
  #- subaru.on
  # Other
  - server-christoph.on
  - server-mathias.on
  - server-matthias.on

backup_storage_rsnapshot_directory: /media/backup/rsnapshot

# überschreiben, falls ein verschlüsselter Datenträger verwendet wird
backup_storage_crypto_device: ""
backup_storage_crypto_mount_points: []

backup_storage_ssh_private_key_path: /root/.ssh/backup-storage_rsa
backup_storage_ssh_public_key_path: "{{ backup_storage_ssh_private_key_path }}.pub"
