- name: ferm - Konfiguration auf olsr2-Interfaces ausweiten
  template:
    src: "ferm/120_olsr2.inc"
    dest: "/etc/ferm/ferm.d/"
  notify: restart ferm

- name: ferm - Alte Konfiguration entfernen
  file:
    path: "/etc/ferm/ferm.d/100_olsr2.inc"
    state: absent
  notify: restart ferm
