- name: network - Aktiviere systemd-networkd Dienst
  systemd:
    name: systemd-networkd.service
    enabled: yes
    masked: no
  notify: restart systemd-networkd

- name: network - Prüfe systemd-networkd Loopback Konfiguration
  stat:
    path: /etc/systemd/network/on-loopback.network
  register: network_systemd_loopback

- name: network - systemd-networkd Loopback Konfiguration anlegen
  template:
    src: on-loopback.network
    dest: /etc/systemd/network/on-loopback.network
  when: not network_systemd_loopback.stat.exists
  notify: 
    - restart systemd-networkd
    - restart olsrd2

- name: network - Prüfe IPv6 ULA Konfiguration
  lineinfile:
    path: /etc/systemd/network/on-loopback.network
    line: "Address={{ olsr_main_ipv6 }}/64"
    state: present
  check_mode: yes
  register: network_systemd_loopback_ula

- name: network - IPv6 ULA auf loopback-Interface konfigurieren
  lineinfile:
    path: /etc/systemd/network/on-loopback.network
    line: |

      [Address]
      Address={{ olsr_main_ipv6 }}/64
  when: network_systemd_loopback_ula.changed
  notify: restart systemd-networkd
