- name: lokalen DNS-Server installieren
  apt:
          pkg:
                  - dnsmasq
                  - resolvconf
          state: present

- name: lokalen DNS-Server konfigurieren
  template:
          src=dnsmasq.conf
          dest=/etc/dnsmasq.d/dns-zone-resolver.conf
  notify: restart dnsmasq

- name: resolv.conf auf lokalen DNS-Server verweisen lassen
  template:
          src=resolv.conf
          dest=/etc/resolv.conf
