#TODO: pip Paket daraus machen, weil dann keine Abhaengigkeit von Python Minor-Version.
- name: checke Python Version
  command: python3 --version
  register: python_string

- name: extrahiere Version
  set_fact:
    python_version_full: "{{ python_string.stdout.split(' ')[1] }}"
- name: extrahiere Version
  set_fact:
    python_version_short: "{{ python_version_full.split('.')[0] ~ '.' ~ python_version_full.split('.')[1] }}"

- name: pruefe Python Version für opennet Modul
  assert:
    that:
      - "python_version_short is version('3.9', '==')"
    fail_msg: "Wir installieren das Opennet-Python-Modul in den python3.9 Ordner. Es wurde aber {{ python_version_short }} gefunden. Der Zielordner muss angepasst werden. Alternativ kannst du das ansible Skript mit dem Parameter '--skip-tags skipPythonVersionCheck' ausführen, um diesen Task zu überspringen."
  tags:
    - always
    - skipPythonVersionCheck

- name: kopiere opennet-Python-Module
  copy:
    src: "opennet/"
    dest: "/usr/local/lib/python3.9/dist-packages/opennet/"
  tags:
    - always
    - skipPythonVersionCheck