#TODO: pip Paket daraus machen, weil dann keine Abhaengigkeit von Python Minor-Version.
- name: checke Python Version
  command: python3 --version
  register: python_string

- name: extrahiere Version
  set_fact:
    python_version_full: "{{ python_string.stdout.split(' ')[1] }}"
- name: extrahiere Version
  set_fact:
    python_version_short: "{{ python_version_full.split('.')[0] ~ '.' ~ python_version_full.split('.')[1] }}"

- name: kopiere opennet-Python-Module
  copy:
    src: "opennet/"
    dest: "/usr/local/lib/python{{ python_version_short }}/dist-packages/opennet/"
  tags:
    - always
    - skipPythonVersionCheck