#TODO: pip Paket daraus machen, weil dann keine Abhaengigkeit von Python Minor-Version.
- name: kopiere opennet-Python-Module
  copy:
    src: "opennet/"
    dest: "/usr/local/lib/python3.7/dist-packages/opennet/"
