- name: kopiere opennet-Python-Module
  copy:
    src: "opennet/"
    dest: "/usr/local/lib/python2.7/dist-packages/opennet/"

- name: Abhaengigkeiten der python-Module installieren
  apt: pkg=python-ipaddr state=present
