- name: restart php-fpm
  service: name="{{ apache2_php_version }}-fpm" state=restarted

- name: restart apache2
  service: name=apache2 state=restarted

- name: restart ferm
  service: name=ferm state=restarted
