- name: Installiere Python und Bibliotheken
  apt:
    pkg:
    - python3
    - python3-lxml #to have a fixed parser for bs4
    - python3-bs4 #BeautifulSoup for parsing (even malformed) HTML
    - python3-requests
    - python3-pip #for ics module installation

- name: Installiere xz-utils damit Hugo via URL installierbar ist
  apt:
    pkg: xz-utils

- name: Installiere neueres Hugo
  apt:
    #install newer version of hugo because for syna theme
    #syna 0.17.4 needs at least hugo 0.76
    #on Debian10 only hugo 0.56 is available
    deb: https://github.com/gohugoio/hugo/releases/download/v0.79.1/hugo_extended_0.79.1_Linux-64bit.deb

- name: Hugo Benutzer anlegen
  user:
    name: "hugo"
    shell: "/bin/bash"

- name: Installiere Python Bibliothek ics via pip
  pip:
    name: ics
    executable: pip3
  become_user: hugo
  become: yes
  become_method: su
  vars:
    #explicitely name python3 here. Else ansible is searching for python2-setuptools
    #because python2 is default value for ansible_python_interpreter
    ansible_python_interpreter: /usr/bin/python3

- name: Clone hugo static-frontpage Repo und Submodules
  git:
    repo: 'https://git.hack-hro.de/opennet-initiative/static-frontpage'
    dest: /home/hugo/static-frontpage
  become_user: hugo
  become: yes
  become_method: su

- name: Erstelle Verzeichnis für statische Webseiten
  file:
    state: directory
    path: /var/www/www.opennet-initiative.de
    owner: hugo

- name: Erstelle Unterverzeichnisse für weitere Webinhalte
  file:
    state: directory
    path: /var/www/www.opennet-initiative.de/download

- name: Installiere Cron-Job für regelmäßige RSS-Aktualisierung
  cron:
    name: "on-hugo-deploy-prod.sh"
    job: "cd /home/hugo/static-frontpage && ./on-hugo-deploy-prod.sh"
    #run at 2:05 each day
    minute: "5"
    hour: "2"
    user: hugo
