- include_tasks: packages.yml
- include_tasks: hostname.yml
- include_tasks: opennet.yml
- include_tasks: admins.yml
- include_tasks: ferm-basic.yml
- include_tasks: opennetca.yml
- include_tasks: change-notifications.yml
- include_tasks: munin-node.yml
- include_tasks: apt-debian.yml
