- include: opennet.yml
- include: munin-node.yml
- include: packages.yml
- include: admins.yml
- include: ferm-basic.yml
- include: opennet-ca.yml
# Entscheidung ueber die Verwendung von metche ist erstmal offen
# siehe "Server-Benachrichtigungen (changetrack/metche)" vom 17.01.2016
# Nach der Klaerung koennen wir den Task wieder aktivieren oder dauerhaft entfernen.
#- include: change-notifications.yml
