- name: munin-node installieren
  apt: state=present pkg=munin-node

- name: Abhaengigkeit fuer vereinfachte IP-basierte Filterung installieren
  apt: state=present pkg=libnet-cidr-perl

- name: munin-Abfrage IP-basiert zulassen
  lineinfile: dest=/etc/munin/munin-node.conf
              state=present
              regexp="^cidr_allow {{ item }}$"
              line="cidr_allow {{ item }}"
              insertafter="^# cidr_deny"
  with_items: "{{munin_servers}}"
  when: workaround_munin_debian_buster_allow_ipv6_only is undefined  # Workaround#001 for Debian Buster
  notify: restart munin-node

# Workaround#001: Folgendes ist Workaround für Debian buster.
- name: munin-Abfrage IP-basiert zulassen (only IPv6)
  lineinfile: dest=/etc/munin/munin-node.conf
              state=present
              regexp="^cidr_allow {{ item }}$"
              line="cidr_allow {{ item }}"
              insertafter="^# cidr_deny"
  with_items: "{{munin_servers_ipv6_buster}}"
  when: workaround_munin_debian_buster_allow_ipv6_only is defined
  notify: restart munin-node

- name: host-spezifische munin-Plugins installieren
  copy:
          src=munin/{{ item }}
          dest=/etc/munin/plugins/{{ item }}
  with_items: "{{ munin_plugins }}"
  notify: restart munin-node
