- name: munin-node installieren
  apt: state=present pkg=munin-node

- name: Abhaengigkeit fuer vereinfachte IP-basierte Filterung installieren
  apt: state=present pkg=libnet-cidr-perl

- name: munin-Abfrage IP-basiert zulassen
  lineinfile: dest=/etc/munin/munin-node.conf
              state=present
              regexp="^cidr_allow {{ item }}$"
              line="cidr_allow {{ item }}"
              insertafter="^# cidr_deny"
  with_items: "{{munin_servers}}"
  notify: restart munin-node
