- name: Willkommensnachricht uebertragen
  template: src=motd
            dest=/etc/motd

# Das Modul funktioniert unter Debian aktuell nicht, da es /etc/timezone statt /etc/localtime
# bearbeitet:
#   https://github.com/ansible/ansible/pull/27546 (unvollstaendig geloest im Oktober 2017)
# Stattdessen verwenden wir vorerst den manuellen (und korrekten) Weg (via /etc/localtime):
#   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813226#10
#- name: Zeitzone setzen
#  timezone:
#    name: "{{ opennet_timezone }}"

- name: Zeitzone setzen
  file:
    path: /etc/localtime
    src: /usr/share/zoneinfo/{{ opennet_timezone }}
    state: link
    # die potentielle Umstellung von Datei auf symlink erfordert "force"
    force: yes
  notify: reconfigure tzdata

- name: locales-Paket installieren
  apt: pkg=locales state=present

- name: Locale erzeugen
  locale_gen:
    name: "{{ opennet_locale_lang }}"
    state: present

- name: Locale konfigurieren (LANG)
  command: update-locale LANG={{ opennet_locale_lang }}
  # Wir könnten in die /etc/default/locale schauen, ob die Handlung notwendig ist, aber damit
  # müssten wir Interna von update-locale nachbilden.
  # Also lieber immer ausführen ohne Änderungen zu berichten.
  changed_when: False

- name: Locale konfigurieren (LANGUAGE)
  command: update-locale LANGUAGE={{ opennet_locale_language }}
  changed_when: False
