- name: apt -- server-relevante Pakete installieren
  apt: pkg={{ item }} state=present
  with_items:
    - bash-completion
    - bzip2    
    - git
    - less
    - locales
    - mc
    - molly-guard
    - ntp
    - psmisc
    - screen
    - tree
    - vim-nox
    - zip

- name: apt -- Debug-Werkzeuge installieren
  apt: pkg={{ item }} state=present
  with_items:
    - bwm-ng
    - dnsutils
    - iftop
    - iotop
    - iperf
    - mtr-tiny
    - netdiag
    - strace
    - tcpdump

- name: apt -- apt-dater-host installieren
  apt: install_recommends=no state=present pkg=apt-dater-host

- name: apt -- acpi-support-base installieren
  apt: install_recommends=no state=present pkg=acpi-support-base

# FIXME: wegen Fehler bei postinst.d/update-initramfs in initramfs-tools (12/2017)
# kann eventuell wieder entfernt werden, wenn die Abhängigkeit upstream gelöst ist
- name: apt -- busybox installieren (initramfs Abhängigkeit)

