- name: apt -- server-relevante Pakete installieren
  apt: pkg={{ item }} state=present
  with_items:
    - ntp
    - locales
    - bzip2    
    - vim-nox
    - less
    - bash-completion
    - mc
    - git
    - tree
    - zip
    - molly-guard

- name: apt -- Debug-Werkzeuge installieren
  apt: pkg={{ item }} state=present
  with_items:
    - tcpdump
    - strace
    - bwm-ng
    - netdiag
    - screen
    - iotop
    - iftop
    - dnsutils
    - mtr-tiny
    - iperf

- name: apt -- apt-dater-host installieren
  apt: install_recommends=no state=present pkg=apt-dater-host

- name: apt -- acpi-support-base installieren
  apt: install_recommends=no state=present pkg=acpi-support-base
