- name: packages -- Server-relevante Pakete installieren
  apt:
    name:
      - bash-completion
      - bzip2    
      - git
      - less
      - locales
      - mc
      - molly-guard
      - ntp
      - psmisc
      # Derzeit (2019) benötigt ansible nur "python-apt" auf der 
      # Client-Seite. Dies wird sich irgendwann ändern.
      - python3-apt
      - screen
      - tree
      - vim-nox
      - zip
      - cron
      - dialog
      - aptitude
      - apt-dater-host
      - acpi-support-base
      - debian-security-support

- name: packages -- Server-relevante Pakete installieren (ab Jessie)
  apt:
    name: needrestart
  when: ansible_distribution_major_version|int >= 8

- name: packages -- Debug-Werkzeuge installieren
  apt:
    name: 
      - bwm-ng
      - dnsutils
      - iftop
      - iotop
      - iperf
      - mtr-tiny
      - netdiag
      - strace
      - tcpdump
      - netcat

- name: packages -- rsyslog installieren (bis Buster)
  apt: install_recommends=no state=present name=rsyslog
  when: ansible_distribution_major_version|int <= 10

- name: packages -- rsyslog / logrotate entfernen (ab Bullseye)
  apt:
    name: 
      - rsyslog
      - logrotate
    state: absent
    purge: yes
  when: ansible_distribution_major_version|int >= 11

# FIXME: wegen Fehler bei postinst.d/update-initramfs in initramfs-tools (12/2017)
# kann eventuell wieder entfernt werden, wenn die Abhängigkeit upstream gelöst ist
- name: packages -- busybox installieren (initramfs Abhängigkeit)
  apt: name=busybox state=present
