- name: packages -- Server-relevante Pakete installieren
  apt:
    name:
      - bash-completion
      - bzip2    
      - git
      - less
      - locales
      - mc
      - molly-guard
      - ntp
      - psmisc
      # Derzeit (2019) benötigt ansible nur "python-apt" auf der 
      # Client-Seite. Dies wird sich irgendwann ändern.
      - python3-apt
      - screen
      - tree
      - vim-nox
      - zip
      - cron
      - dialog
      - aptitude
      - apt-dater-host
      - acpi-support-base
      - debian-security-support
      - wget
      - whiptail

- name: packages -- Server-relevante Pakete installieren (ab Jessie)
  apt:
    name: needrestart
  when: ansible_distribution_major_version|int >= 8

- name: packages -- Debug-Werkzeuge installieren
  apt:
    name: 
      - bwm-ng
      - dnsutils
      - iftop
      - iotop
      - iperf
      - mtr-tiny
      - netdiag
      - strace
      - tcpdump
      
- name: packages -- Debug-Werkzeuge installieren (bis Buster)
  apt:
    name: 
      - netcat
  when: ansible_distribution_major_version|int <= 10

- name: packages -- Debug-Werkzeuge installieren (ab Bullseye)
  apt:
    name: 
      - netcat-traditional
  when: ansible_distribution_major_version|int > 10

- name: packages -- rsyslog installieren (bis Buster)
  apt: 
    name: rsyslog 
    install_recommends: no 
  when: ansible_distribution_major_version|int <= 10

- name: packages -- rsyslog entfernen (ab Bullseye)
  apt:
    name: rsyslog
    state: absent
    purge: yes
  when: ansible_distribution_major_version|int >=11 

- name: packages -- Lese installierte Debian Pakete (ab Bullseye)
  package_facts:
    manager: auto
  when: ansible_distribution_major_version|int >=11

# TODO: avoid removing logrotate on virtualization and backup hosts
# currently the package_fact check is not an optimal solution
- name: packages -- logrotate entfernen (ab Bullseye)
  apt:
    name: logrotate
    state: absent
    purge: yes
  when: ( ansible_distribution_major_version|int >=11 ) and ( "'libvirt-daemon-system' not in ansible_facts.packages" ) == true and ( "'rsnapshot' not in ansible_facts.packages" ) == true

# FIXME: wegen Fehler bei postinst.d/update-initramfs in initramfs-tools (12/2017)
# kann eventuell wieder entfernt werden, wenn die Abhängigkeit upstream gelöst ist
- name: packages -- busybox installieren (initramfs Abhängigkeit)
  apt: name=busybox state=present
