- name: ca - CA Name ausgeben
  debug: msg="{{ ca }}"

- name: ca - CA / Sub CA anlegen
  file:
    path: "{{ opennetca_path_user }}/ca/{{ ca }}"
    state: directory
    owner: "{{ opennetca_user }}"
    group: "{{ opennetca_user }}"

- name: ca - Opennet CA Software kopieren 
  copy:
    src: "{{ opennetca_path_user }}/src/ca/{{ line_item }}"
    dest: "{{ opennetca_path_user }}/ca/{{ ca }}/{{ line_item }}"
    owner: "{{ opennetca_user }}"
    group: "{{ opennetca_user }}"
    mode: preserve
    remote_src: yes
  with_items: 
    - crl.sh
    - opennetca_crldownload.sh
    - opennetca.sh
    - revoke.sh
    - sign.sh
    - list.sh
    - opennetca_htmlview.sh
    - revoke_batch.sh
    - sign_batch.sh
  loop_control:
    loop_var: line_item

- name: ca - Unterverzeichnisse für CA erstellen
  file:
    path: "{{ opennetca_path_user }}/ca/{{ ca }}/{{ line_item }}/"
    state: directory
    owner: "{{ opennetca_user }}"
    group: "{{ opennetca_user }}"
  with_items:
    - cert
    - crl
    - .backup
  loop_control:
    loop_var: line_item

- name: ca - Unterverzeichnis CSR erstellen (root)
  file:
    path: "{{ opennetca_path_user }}/ca/{{ ca }}/csr"
    state: directory
    owner: "{{ opennetca_user }}"
    group: "{{ opennetca_user }}"
  when: ca == "root"

- name: ca - Unterverzeichnis CSR erstellen (non-root)
  file:
    src: "{{ opennetca_path_csr }}"
    dest: "{{ opennetca_path_user }}/ca/{{ ca }}/csr"
    state: link
  when: ca != "root"

- name: ca - Index und Serial für CA anlegen
  copy:
    content: ""
    dest: "{{ opennetca_path_user }}/ca/{{ ca }}/{{ line_item }}"
    force: no
    owner: "{{ opennetca_user }}"
    group: "{{ opennetca_user }}"
  with_items:
    - index.txt
    - serial.txt
  loop_control:
    loop_var: line_item

- name: ca - Konfiguration (Opennet CA) für CA erstellen
  template:
    src: opennetca.cfg
    dest:  "{{ opennetca_path_user }}/ca/{{ ca }}/"
    owner: "{{ opennetca_user }}"
    group: "{{ opennetca_user }}"

- name: ca - Konfiguration (OpenSSL) für CA erstellen
  template:
    src: opennetca_openssl.conf 
    dest: "{{ opennetca_path_user }}/ca/{{ ca }}/opennet-{{ ca }}.ca.on_{{ opennetca_year }}.conf"
    owner: "{{ opennetca_user }}"
    group: "{{ opennetca_user }}"
