- name: install - Werkzeuge installieren
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - openssl
    - jq
    - mutt
    - moreutils

- name: install - Benutzer anlegen
  user:
    name: "{{ opennetca_user }}"
    groups: "{{ opennetca_user_web }}"
    shell: "{{ opennetca_user_shell }}"

- name: install - Opennet CA Software via Git übertragen 
  git:
    repo: "{{ opennetca_src }}"
    dest: "{{ opennetca_path_user }}/src"
    force: yes

- name: install - Verzeichnisse anlegen
  file:
    path: "{{ opennetca_path_user }}/{{ item }}"
    state: directory
    owner: "{{ opennetca_user }}"
    group: "{{ opennetca_user }}"
  with_items:
    - ca
    - csr
