- name: install - Werkzeuge installieren
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - openssl
    - jq
    - bsd-mailx
    - mutt
    - moreutils

- name: install - Benutzer anlegen
  user:
    name: "{{ opennetca_user }}"
    groups: "{{ opennetca_user_web }}"
    shell: "{{ opennetca_user_shell }}"

- name: install - Opennet CA Software via Git übertragen 
  git:
    repo: "{{ opennetca_src }}"
    dest: "{{ opennetca_path_user }}/src"
    force: yes

- name: install - Verzeichnisse anlegen
  file:
    path: "{{ opennetca_path_user }}/{{ item }}"
    state: directory
    owner: "{{ opennetca_user }}"
    group: "{{ opennetca_user }}"
  with_items:
    - ca
    - csr

- name: install - Hinweis kopieren
  copy:
    src: "{{ opennetca_path_user }}/src/README"
    dest: "{{ opennetca_path_user }}/"
    owner: "{{ opennetca_user }}"
    group: "{{ opennetca_user }}"
    mode: preserve
    remote_src: yes

- name: install - Mail (Mutt) GPG konfigurieren
  lineinfile:
    path: "{{ opennetca_mail_gpgrc }}"
    regexp: "crypt_use_gpgme"
    line: "set crypt_use_gpgme=no"
