- name: install - CA / Sub CA anlegen
  file:
    path: "{{ opennetca_path_user }}/ca/{{ ca }}"
    state: directory
    owner: "{{ opennetca_user }}"
    group: "{{ opennetca_user }}"

- name: install - Opennet CA Software kopieren 
  copy:
    src: "{{ opennetca_path_user }}/src/ca/{{ line_item }}"
    dest: "{{ opennetca_path_user }}/ca/{{ ca }}/{{ line_item }}"
    owner: "{{ opennetca_user }}"
    group: "{{ opennetca_user }}"
    mode: preserve
    remote_src: yes
  with_items: 
    - crl.sh
    - opennetca_crldownload.sh
    - opennetca.sh
    - revoke.sh
    - sign.sh
    - list.sh
    - opennetca_htmlview.sh
    - revoke_batch.sh
    - sign_batch.sh
  loop_control:
    loop_var: line_item

- name: install - Unterverzeichnisse für CA erstellen
  file:
    path: "{{ opennetca_path_user }}/ca/{{ ca }}/{{ line_item }}/"
    state: directory
    owner: "{{ opennetca_user }}"
    group: "{{ opennetca_user }}"
  with_items:
    - cert
    - crl
    - csr
    - .backup
  loop_control:
    loop_var: line_item

# Workaround, see https://github.com/ansible/ansible/issues/21342
- name: install - Index und Serial für CA anlegen
#  file:
#    path: "{{ opennetca_path_user }}/ca/{{ ca }}/{{ line_item }}"
#    state: touch
#    modification_time: preserve
  copy:
    content: ""
    dest: "{{ opennetca_path_user }}/ca/{{ ca }}/{{ line_item }}"
    force: no
    owner: "{{ opennetca_user }}"
    group: "{{ opennetca_user }}"
  with_items:
    - index.txt
    - serial.txt
  loop_control:
    loop_var: line_item

- name: install - Konfiguration für CA erstellen
  template:
    src: opennetca.cfg
    dest:  "{{ opennetca_path_user }}/ca/{{ ca }}/"
    owner: "{{ opennetca_user }}"
    group: "{{ opennetca_user }}"
