- name: config-archive - Base URL setzen
  lineinfile:
    path: "{{ mailinglist_config_web }}"
    regexp: '^base_url:'
    line: "base_url: https://{{ mailinglist_domain }}/hyperkitty'"
  notify:
    - restart mailman3 
    - restart mailman3-web
