olsr_routing_table_id: 120
olsr_routing_table_name: olsrd

olsr_nameservice_announcements: []
olsr_extra_settings: ""

# einzelne Hosts, Gruppen oder Rollen koennen diese Liste definieren (IPv4-Adressen ohne Netzmaske)
olsr_hna_announcements_ipv4: []

# Dieser Wert (typischerweise ein Vielfaches von 2) wird zur Markierung von
# Paketen verwendet, die vorranging _nicht_ via olsr geroutet werden sollen.
non_olsr_policy_routing_mark: 32

non_olsr_interfaces:
  - "{{ wan_interface|default('nonexisting') }}"

# Debian Packages
olsr_debian_url: "https://downloads.opennet-initiative.de/debian"
olsr_debian11_amd: "olsrd_0.9.8-3_amd64+deb11.deb"
olsr_plugins_debian11_amd: "olsrd-plugins_0.9.8-3_amd64+deb11.deb"
olsr_debian12_arm: "olsrd_0.9.8-4_arm64+deb12.deb"
olsr_plugins_debian12_arm: "olsrd-plugins_0.9.8-4_arm64+deb12.deb"
