- name: Installiere Hugo + Python
  apt:
    pkg:
    - hugo
    - python3
    - python3-lxml #to have a fixed parser for bs4
    - python3-bs4 #BeautifulSoup for parsing (even malformed) HTML

- name: Clone hugo static-frontpage Repo und Submodules
  git:
    repo: 'https://git.hack-hro.de/opennet-initiative/static-frontpage'
    dest: /opt/hugo

# Spaeter soll der User neu generierte Seiten nach
#  /var/www/www.opennet-initaitive.de kopieren koennen
- name: Setze www-data als Eigentuemer von /opt/hugo
  file:
    path: /opt/hugo
    owner: www-data
    recurse: yes

- name: Erstelle Verzeichnis für statische Webseiten
  file:
    state: directory
    path: /var/www/www.opennet-initiative.de
    owner: www-data

#TODO
#- name: Aktiviere cron-Job für regelmäßige Hugo-RSS-Aktualisierung
#  cron: name=on-hugo-deploy.sh
#        job="/usr/local/sbin/on-hugo-deploy.sh"
#        #run at 2:05 each day
#        minute=5
#        hours=2
