- name: git-install - Software installieren
  apt: 
    name: gitolite

- name: git-install - Benutzer anlegen
  user:
    name: "{{ gitserver_git_user }}"
    shell: "{{ gitserver_git_shell }}"

- name: git-install - Verzeichnisse anlegen
  file:
    path: "{{ gitserver_git_path }}/{{ item }}"
    state: directory
    owner: "{{ gitserver_git_user }}"
    group: "{{ gitserver_git_user }}"
    mode: "{{ gitserver_git_mode }}"
  with_items:
    - keys
    - repositories

- name: git-install - SSH Public Keys kopieren
  copy:
    src: "git/keys/{{ item.split('.')[0] }}.pub"
    dest: "{{ gitserver_git_path }}/keys/"
    owner: "{{ gitserver_git_user }}"
    group: "{{ gitserver_git_user }}"
  with_items: "{{ gitserver_allowed_users }}"

- name: git-install - Gitolite Dateirechte (UMASK) setzen
  replace:
    path: "{{ gitserver_git_path }}/.gitolite.rc"
    regexp: 'UMASK.*=>.*'
    replace: "UMASK                           =>  {{ gitserver_git_umask }},"
    backup: yes
