- name: user - Benutzer anlegen
  user:
    name: "{{ gitserver_git_user }}"
    comment: "Git Server"
    home: "{{ gitserver_git_path }}"
    shell: "/bin/bash"
    system: yes

- name: user - Verzeichnisse anlegen
  file:
    path: "{{ gitserver_git_path }}/{{ item }}"
    state: directory
    owner: "{{ gitserver_git_user }}"
    group: "{{ gitserver_git_user }}"
    mode: "{{ gitserver_git_mode }}"
  with_items:
    - keys
    - repositories

- name: user - SSH Public Keys kopieren
  copy:
    src: "keys/{{ item }}"
    dest: "{{ gitserver_git_path }}/keys/"
    owner: "{{ gitserver_git_user }}"
    group: "{{ gitserver_git_user }}"
  with_items: "{{ gitserver_allowed_users }}"
