- name: restart libvirtd
  service: name=libvirtd state=restarted

- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: restart ferm
  service: name=ferm state=restarted

# systemd kennt "reload" nicht - also "restart"
- name: restart procps
  service: name=procps state=restarted
