- name: Opennet apt repo einbinden (TODO)
  # TODO: einrichten, sobald repo final vorhanden ist
  command: /bin/false
  ignore_errors: yes
  changed_when: False

- name: apt -- on-mitgliedsantrag Paket aus Repo installieren (TODO)
  apt:
          pkg: on-mitgliedsantrag
          state: present
  ignore_errors: yes # TODO: entfernen, sobald es ein finales ONI apt repo gibt

# TODO: die unteren beiden Worarounds löschen, sobald ONI apt repo vorhanden ist
- name: Workaround -- installiere on-mitgliedsantrag manuell (1/2)
  apt:
          pkg:
                  - libphp-phpmailer
                  - pdftk
          state: present

- name: Workaround -- installiere on-mitgliedsantrag manuell (2/2)
  apt:
          deb: http://dev.opennet-initiative.de/export/769439e4d3acfeab7475e57330323cc5af1ed9c3/on_mitgliedsantrag/tmp-bin/on-mitgliedsantrag_1.0_all.deb
