- name: run on-policy-routing-olsr2
  command: /etc/network/if-up.d/on-policy-routing-olsr2

- name: restart ferm
  service: name=ferm state=restarted

- name: restart olsrd2
  service: name=olsrd2 state=restarted

- name: restart systemd-networkd
  systemd: name=systemd-networkd.service state=restarted
