- name: restart ferm
  service: name=ferm state=restarted

- name: restart openvpn
  service: name=openvpn state=restarted

- name: restart sysctl
  service: name=procps state=restarted

- name: restart olsrd
  service: name=olsrd state=restarted

- name: restart openbsd-inetd
  service: name=openbsd-inetd state=restarted

- name: restart munin-node
  service: name=munin-node state=restarted

- name: run rc.local
  command: /etc/rc.local

- name: restart systemd-networkd
  systemd: name=systemd-networkd.service state=restarted

- name: restart isc-dhcp-server
  service: name=isc-dhcp-server state=restarted

- name: restart radvd
  service: name=radvd state=restarted

- name: reload apparmor
  service: name=apparmor state=reloaded
