- name: trac-import - Datenbank übertragen
  copy:
    src: "import/trac.db"
    dest: "{{ opennetdev_trac_path }}/db/trac.db"
    owner: "{{ opennetdev_trac_user_web }}"
    group: "{{ opennetdev_trac_user_web }}"

- name: trac-import - Datenbank Tabellen bereinigen
  command: "sqlite3 {{ opennetdev_trac_path }}/db/trac.db 'DELETE FROM {{ item }};'"
  with_items: "{{ opennetdev_trac_dbimport_delete }}"

- name: trac-import - Datenbank IP Adressen anonymisieren
  command: "sqlite3 {{ opennetdev_trac_path }}/db/trac.db 'UPDATE {{ item }} SET ipnr=\"127.0.0.1\";'"
  with_items: "{{ opennetdev_trac_dbimport_ipanon }}"

# TODO: attachment location changed in Trac 1.x; currently we are migrating from 0.12
- name: trac-import - Anhänge übertragen
  unarchive:
    src: "import/attachments.tar.gz"
    dest: "{{ opennetdev_trac_path }}/"
    owner: "{{ opennetdev_trac_user_web }}"
    group: "{{ opennetdev_trac_user_web }}"

- name: trac-import - Upgrade starten
  command: "trac-admin {{ opennetdev_trac_path }}/ upgrade"

- name: trac-import - Verzeichnisrechte anpassen
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ opennetdev_trac_user_web }}"
    group: "{{ opennetdev_trac_user_web }}"
  with_items:
    - "{{ opennetdev_trac_path }}"
    - "{{ opennetdev_trac_path_web }}"
