- name: trac-install - Software installieren
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - trac
    - trac-bitten
    - libapache2-mod-wsgi
    # TODO: reenable trac-announcer once available in Debian Buster
    #- trac-announcer

- name: trac-install - Verzeichnisse anlegen
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ opennetdev_trac_user_web }}"
    group: "{{ opennetdev_trac_user_web }}"
  with_items:
    - "{{ opennetdev_trac_path }}"
    - "{{ opennetdev_trac_path_web }}"

- name: trac-install - Umgebung initialisieren
  command: "trac-admin {{ opennetdev_trac_path }} initenv '{{ opennetdev_trac_desc }}' '{{ opennetdev_trac_db }}'"
  args:
    creates: "{{ opennetdev_trac_path }}/conf/{{ opennetdev_trac_ini }}"

- name: trac-install - Webseite initialisieren
  command: "trac-admin {{ opennetdev_trac_path }} deploy {{ opennetdev_trac_path_web }}"
  args:
    creates: "{{ opennetdev_trac_path_web }}/cgi-bin/{{ opennetdev_trac_cgi }}"

- name: trac-install - Dateirechte anpassen
  file:
    path: "{{ item }}"
    owner: "{{ opennetdev_trac_user_web }}"
    group: "{{ opennetdev_trac_user_web }}"
    recurse: yes
  with_items:
    - "{{ opennetdev_trac_path }}"
    - "{{ opennetdev_trac_path_web }}"

- name: trac-install - Opennet Logo kopieren
  copy:
    src: "{{ opennetdev_trac_logo }}"
    dest: "{{ opennetdev_trac_path_web }}/htdocs/site/"
    owner: "{{ opennetdev_trac_user_web }}"
    group: "{{ opennetdev_trac_user_web }}"

- name: trac-install - Opennet Favicon kopieren
  copy:
    src: "{{ opennetdev_trac_icon }}"
    dest: "{{ opennetdev_trac_path_web }}/htdocs/site/"
    owner: "{{ opennetdev_trac_user_web }}"
    group: "{{ opennetdev_trac_user_web }}"

- name: trac-install - Robots Datei kopieren
  copy:
    src: "robots.txt"
    dest: "{{ opennetdev_trac_path_web }}/htdocs/site/"
    owner: "{{ opennetdev_trac_user_web }}"
    group: "{{ opennetdev_trac_user_web }}"
