- name: buildbot - Software installieren
  apt:
    name: 
      - buildbot
      - python3-pip
    install_recommends: no

- name: buildbot - Installiere Webinterface via pip
  pip:
    name:
      - buildbot-www
      - buildbot-waterfall-view
      - buildbot-console_view
      - buildbot-grid-view
  notify: restart buildbot

- name: buildbot - Controller Dienst freischalten
  lineinfile:
    dest: "/etc/default/buildbot"
    backrefs: yes
    regexp: "^MASTER_ENABLED"
    line: "MASTER_ENABLED[1]=1"
  notify: restart buildbot

- name: buildbot - Controller Name setzen
  lineinfile:
    dest: "/etc/default/buildbot"
    backrefs: yes
    regexp: "^MASTER_NAME"
    line: "MASTER_NAME[1]=\"{{ buildbot_controller_name }}\""
  notify: restart buildbot

- name: buildbot - Controller basedir setzen
  lineinfile:
    dest: "/etc/default/buildbot"
    backrefs: yes
    regexp: "^MASTER_BASEDIR"
    line: "MASTER_BASEDIR=\"{{ buildbot_controller_path }}\""
  notify: restart buildbot

- name: buildbot - Controller Autostart aktivieren
  systemd:
    name: "buildbot@{{ buildbot_controller_name }}"
    enabled: yes
  notify: restart buildbot
