- name: mitgliederverwaltung - Konfiguration (siteconfig) übertragen
  template: 
    src: moin-site.py
    dest: /etc/moin/mitgliederverwaltung.py

- name: mitgliederverwaltung - Verzeichnisse anlegen
  file: 
    dest: "{{ item }}"
    state: directory
    owner: "{{ mitgliederverwaltung_user }}"
    group: "{{ mitgliederverwaltung_user }}"
    mode: 0755
  with_items:
    - "{{ mitgliederverwaltung_web_path }}"
    - "{{ mitgliederverwaltung_app_path }}"
    - "{{ mitgliederverwaltung_app_path }}/underlay"

- name: mitgliederverwaltung - Logo und Favicon kopieren
  copy:
    src: "{{ item }}"
    dest: "{{ mitgliederverwaltung_web_path }}"
  with_items:
    - opennetlogo.png
    - favicon.ico

- name: mitgliederverwaltung - Macros kopieren
  copy: 
    src: macro/
    dest: "{{ mitgliederverwaltung_app_path }}/data/plugin/macro/"

- name: mitgliederverwaltung - rsync installieren
  apt:
    name: rsync

# TODO: replace with ansible-galaxy "ansible.posix.syncronize"?
- name: mitgliederverwaltung - Underlay aktualisieren (via rsync)
  shell: rsync --archive --chown\={{ mitgliederverwaltung_user }}:{{ mitgliederverwaltung_user }} /usr/share/moin/underlay {{ mitgliederverwaltung_app_path }}/underlay
  changed_when: False
 
- name: mitgliederverwaltung - Sind Daten für MoinMoin Installation bereits vorhanden?
  stat: path=/var/lib/mitgliederverwaltung/data/
  check_mode: no
  register: moinmoin_data_installed

- name: mitgliederverwaltung - Backup der alten MoinMoin Installation zur neuen Installation kopieren
  fail:
    msg: TODO - Du musst das Backup des data/ Verzeichnisses per Hand selbst einspielen. Siehe auch roles/mitgliederverwaltung-server/README.md
  when: moinmoin_data_installed.stat.isdir is not defined
