- name: cron - Aktiviere Aufgabe für regelmäßige Aktualisierung
  cron: 
    name: on-update-domain-proxy
    job: "/usr/local/sbin/on-update-domain-proxy --log-level info --log-file {{ domain_proxy_web_path }}/status/update.log"
    minute: "*/15"
