- name: slt - Installiere Software
  apt: 
    name: slt
    state: present

# TODO: die folgenden beiden Aktionen können entfernt werden, sobald https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828188 in stable ist
- name: slt - Init-Skript für slt kopieren
  copy: 
    src: slt/init
    dest: /etc/init.d/slt
    mode: 755

- name: slt - Default-Datei kopieren
  copy: 
    src: slt/default
    dest: /etc/default/slt

- name: slt - Dienst aktivieren
  service: 
    name: slt 
    enabled: yes
