- name: Erzeuge www-Verzeichnis für Konfigurationen und Logs
  file: dest={{ domain_proxy_www_path }}/{{ short_hostname }}
        state=directory

# forcieren des Symlinks, da bei der Erstinstallation die slt.conf fehlt
- name: Verlinke Konfigurationsdateien ins www-Verzeichnis
  file: src={{ item.src }}
        dest={{ domain_proxy_www_path }}/{{ short_hostname }}/{{ item.dest }}
        state=link
        force=yes
  with_items:
    - { dest: apache2.conf, src: "/etc/apache2/sites-enabled/{{ domain_proxy_apache2_config_name }}.conf" }
    - { dest: slt.conf, src: /etc/slt.conf }
