- name: downloads-buildbot - Überprüfe Verzeichnis
  stat:
    path: "{{ downloads_buildbot_path }}"
  register: downloads_buildbot

- name: downloads-buildbot - Status des Verzeichnisses auswerten
  fail:
    msq: "TODO - Du musst die Partition und Verzeichnis {{ downloads_buildbot_path }} zunächst per Hand angelegt haben. Siehe auch roles/download-server/README.md"
  when: downloads_buildbot.stat.isdir is not defined

- name: downloads-buildbot - Verzeichnis Eigner setzen
  file:
    path: "{{ downloads_buildbot_path }}"
    state: directory
    owner: "{{ downloads_buildbot_user }}"
    group: "{{ downloads_buildbot_user }}"

- name: downloads-buildbot - Benutzer anlegen
  user:
    name: buildbot
    comment: "Buildbot Worker Upload"
    create_home: no
    home: "{{ downloads_buildbot_path }}"
    shell: "/bin/bash"
    system: yes

- name: downloads-buildbot - Export-Verzeichnis anlegen
  file:
    path: "{{ downloads_buildbot_path }}/{{ downloads_buildbot_export }}"
    state: directory
    owner: "{{ downloads_buildbot_user }}"
    group: "{{ downloads_buildbot_user }}"
