- name: install - Werkzeuge installieren
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - httpie
    - jq

- name: install - Benutzer anlegen
  user:
    name: "{{ homematic_user }}"
    system: yes
    shell: "{{ homematic_user_shell }}"

- name: Verzeichnis für CLI Skript anlegen
  file:
    path: "{{ homematic_path_user }}"
    state: directory
    owner: "{{ homematic_user }}"
    group: "{{ homematic_user }}"

- name: install - CLI Skripte übertragen
  copy:
    src: "cli/{{ item }}"
    dest: "{{ homematic_path_user }}"
    owner: "{{ homematic_user }}"
    group: "{{ homematic_user }}"
    mode: preserve
  with_items:
   - homematic.sh
   - lifxctl.py
   - lifxctl.sh

# only copy if file not exists, do not override
- name: install - CLI Skripte Konfiguration anlegen
  copy:
    src: "cli/{{ item }}"
    dest: "{{ homematic_path_user }}"
    owner: "{{ homematic_user }}"
    group: "{{ homematic_user }}"
    force: no
  with_items:
    - homematic.cfg
    - lifxctl.cfg

- name: install - CLI Skript Logfile prüfen
  stat:
    path: "{{ homematic_log }}"
  register: homematic_log_stat

# create empty file if not exists
- name: install - CLI Skript Logfile anlegen
  file:
    path: "{{ homematic_log }}"
    state: touch
  when: homematic_log_stat.stat.exists == false

# always set permissions and owner/group
- name: install - CLI Skript Logfile Berechtigungen setzen
  file:
    path: "{{ homematic_log }}"
    owner: "{{ homematic_user }}"
    group: "{{ homematic_user_web }}"
    mode: g+w
