- name: restart ferm
  service: name=ferm state=restarted

- name: restart openvpn
  service: name=openvpn state=restarted sleep=5

- name: restart sysctl
  service: name=procps state=restarted

- name: restart olsrd
  service: name=olsrd state=restarted

# der "deactivate"-Handler muss vor dem "activate"-Handler stehen
# (nicht die Reihenfolge der Ausloesung im Prozess, sondern die der Aufzaehlung in dieser Datei ist relevant)
- name: deactivate main_ip
  command: ifdown lo:0

- name: activate main_ip
  command: ifup lo:0

- name: restart bind
  service: name=bind9 state=restarted

