- name: firewall - UGW-Regeln und Verkehrsverbote kopieren
  template:
    src=ferm/{{ item }}
    dest=/etc/ferm/ferm.d/
  with_items:
    - 300_on-block-access.inc
    - 330_ugw.inc
  notify: restart ferm
