- name: munin -- OpenVPN-Plugin fuer munin aktiveren
  copy: src=munin/openvpn_multiple
        dest=/etc/munin/plugins/
        mode=0755
  notify: restart munin-node

- name: munin -- OpenVPN-Plugins konfigurieren
  copy: src=munin/openvpn_multiple.conf
        dest=/etc/munin/plugin-conf.d/openvpn_multiple
  notify: restart munin-node

- name: munin -- OpenVPN-Tunnel aufzeichnen
  file: state=link
        src=/usr/share/munin/plugins/{{ item.source }}
        dest=/etc/munin/plugins/{{ item.target }}
  with_items:
    - { source: "if_", target: "if_{{ openvpn_users_interface }}" }
    - { source: "if_err_", target: "if_err_{{ openvpn_users_interface }}" }
    - { source: "if_", target: "if_{{ openvpn_ugw_interface }}" }
    - { source: "if_err_", target: "if_err_{{ openvpn_ugw_interface }}" }
  notify: restart munin-node

