- name: Nameserver installieren
  apt: state=present pkg=bind9

- name: Nameserver konfigurieren
  template: force=yes
            src=bind9.conf
            dest=/etc/bind/named.conf.local
  notify: restart bind

