- name: Paket-Weiterleitung erlauben
  lineinfile:
        create=yes
        line="{{ item.key }}={{ item.value }}"
        regexp="{{ item.key }}="
        dest=/etc/sysctl.d/opennet.conf
  with_items:
    - { key: "net.ipv4.ip_forward", value: 1}
    # Reverse-Path-Filterung kann aufgrund moeglicher asymmetrischer Routen nur im "loose"-Modus (=2) erfolgen
    # siehe admin-Mailingliste, "rp_filter auf UGW-Servern", Mon, 18 Jan 2016 00:09:15 +0100
    - { key: "net.ipv4.conf.all.rp_filter", value: 2}
  notify: restart sysctl

# bei einer Aenderung der olsr_main_ip loeschen wir den lo:0-Eintrag aus der interfaces-Datei
- name: konfligierende Main-IP entfernen
  command: sed -i '/^auto lo:0$/,/netmask/d' /etc/network/interfaces
  when: ansible_lo_0 is defined and ansible_lo_0["ipv4"]["address"] != olsr_main_ip
  notify: deactivate olsr_main_ip

- name: Main-IP als Alias auf loopback-Interface konfigurieren
  lineinfile: state=present
              dest=/etc/network/interfaces
              regexp="^auto lo:0$"
              line="auto lo:0\niface lo:0 inet static\n\taddress {{ olsr_main_ip }}\n\tnetmask 255.255.255.255\n"
  when: ansible_lo_0 is not defined or ansible_lo_0["ipv4"]["address"] != olsr_main_ip
  notify:
   - activate olsr_main_ip
   # olsrd ignoriert nameservice-Eintraege ohne aktive olsr_main_ip - also nochmal neustarten
   - restart olsrd

