- name: networking - Paket-Weiterleitung erlauben
  lineinfile:
    create: yes
    line: "{{ item.key }}={{ item.value }}"
    regexp: "{{ item.key }}="
    dest: /etc/sysctl.d/opennet.conf
  with_items:
    - { key: "net.ipv4.ip_forward", value: 1}
    # Reverse-Path-Filterung kann aufgrund moeglicher asymmetrischer 
    # Routen nur im "loose"-Modus (=2) erfolgen
    # siehe admin-Mailingliste, "rp_filter auf UGW-Servern", 
    # Mon, 18 Jan 2016 00:09:15 +0100
    - { key: "net.ipv4.conf.all.rp_filter", value: 2}
  notify: restart sysctl

# Nach der Konfiguration des loopback-Interface wollen wir die 
# primaere UGW-Mesh-IP auf dem Interface konfigurieren.
- name: networking - Main-IP auf loopback-Interface konfigurieren
  template:
    src: on-loopback.network
    dest: /etc/systemd/network/on-loopback.network
  notify: restart systemd-networkd
