# Wir verwenden ein altes "openvpn_status"-PHP-Skript zur Visualisierung der aktuellen
# OpenVPN-Client-Verbindungen. Da wir nginx für die "domain-proxy"-Funktion verwenden,
# und nginx nicht direkt php-Code ausführen mag, erstellen wir via cron-Job regelmäßig
# den Output des PHP-Skripts und stellen es via nginx statisch zur Verfügung.

- name: php installieren (nicht stretch)
  apt: name=php5-cli state=present
  when: ansible_distribution_release != "stretch"

- name: php installieren (stretch)
  apt: name=php-cli state=present
  when: ansible_distribution_release == "stretch"

- name: nginx installieren
  apt: name=nginx-light state=present

- name: nginx-Proxy-Konfiguration fuer UGW-Status übertragen
  template: src=nginx/usergw
            dest=/etc/nginx/sites-available/
  notify: reload nginx

- name: nginx-Proxy-Konfiguration fuer UGW-Status aktivieren
  file: src=../sites-available/usergw
        dest=/etc/nginx/sites-enabled/usergw
        state=link
  notify: reload nginx

- name: vpnstatus - Verzeichnis anlegen
  file: state=directory
        dest=/var/www/vpnstatus

- name: vpnstatus - PHP-Skript uebertragen
  copy: src=openvpn/openvpn_clients.php
        dest=/var/www/vpnstatus/

- name: vpnstatus - PHP-Konfiguration uebertragen
  template: src=vpnstatus.php
            dest=/var/www/vpnstatus/index.php

- name: vpnstatus - regelmäßig neu erstellen
  cron: name="vpnstatus aktualisieren"
        job="php /var/www/vpnstatus/index.php >/var/www/vpnstatus/index.html"
        minute="*/3"
