- name: apt -- moinmoin + apache2 relevante Pakete installieren
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - python-moinmoin
    - apache2
    - bzip2

- name: DocumentRoot Verzeichnis anlegen
  file: state=directory
        dest=/var/www/mitgliederverwaltung/
        owner=www-data
        group=www-data
        mode=755

- name: MoinMoin Haupt-Verzeichnis anlegen
  file: state=directory
        dest=/var/lib/mitgliederverwaltung/
        owner=www-data
        group=www-data
        mode=755

- name: MoinMoin underlay-Verzeichnis von frischer MoinMoin Installation kopieren
  copy: src=/usr/share/moin/underlay/
        dest=/var/lib/mitgliederverwaltung/underlay/

#- name: MoinMoin data-Verzeichnis grundauf neu generieren, wenn z.B. leeres MoinMoin getestet werden soll.
#  copy: src=/usr/share/moin/data
#        dst=/var/lib/mitgliederverwaltung/data
#        owner=www-data
#        group=www-data
#        mode=700

- name: MoinMoin data-Verzeichnis von alter MoinMoin Installation kopieren
  unarchive:
    src=/on-tmp/data.tar.bz2
    dest=/var/lib/mitgliederverwaltung/

- name: Apache site config kopieren
  template:
    src=wiki-mitgliederverwaltung.conf
    dest=/etc/apache2/sites-available/

- name: Apache basic auth htpasswd kopieren
  copy: src=/on-tmp/wiki-mitgliederverwaltung.htpasswd
        dest=/etc/apache2/

- name: MoinMoin Wiki Config kopieren
  copy: src=etc/moin/ 
        dest=/etc/moin/

- name: Zertifikatsverzeichnis anlegen
  file: state=directory
        dest=/var/lib/dehydrated/certs/mitgliederverwaltung.opennet-initiative.de/
        owner=www-data
        group=www-data
        mode=700

- name: SSL cert fuer HTTPS generieren. Wenn es keine Certs bisher gibt, generiere self-signed certs neu.
  copy: 
    src={{ item }}
    dest=/var/lib/dehydrated/certs/mitgliederverwaltung.opennet-initiative.de/
    force=no #do not overwrite files
  with_fileglob:
    - certs-self-signed/*

- name: activate autostart of Apache
  service:
    name: apache2
    enabled: yes

- name: Apache activate cgid mod #apache has MPM therefore we need cgid instead of cgi
  apache2_module:
    state: present
    name:  cgid

- name: Apache activate SSL mod
  apache2_module:
    state: present
    name:  ssl

- name: Apache activate wiki-mitgliederverwaltung site
  command: a2ensite wiki-mitgliederverwaltung
  notify: restart apache

- name: Apache restart
  service:
    name: apache2
    state: restarted

