- name: apt -- moinmoin Paket installieren
  apt:
          pkg: python-moinmoin
          state: present

- name: DocumentRoot Verzeichnis anlegen
  file: state=directory
        dest=/var/www/mitgliederverwaltung/
        owner=www-data
        group=www-data
        mode=755

- name: MoinMoin Haupt-Verzeichnis anlegen
  file: state=directory
        dest=/var/lib/mitgliederverwaltung/
        owner=www-data
        group=www-data
        mode=755

- name: MoinMoin wiki-farm-Konfiguration kopieren
  copy: src=moin-farmconfig.py
        dest=/etc/moin/farmconfig.py

- name: MoinMoin wiki-farm-Konfiguration kopieren
  template: src=moin-site.py
            dest=/etc/moin/mitgliederverwaltung.py

- name: MoinMoin underlay-Verzeichnis vorhanden?
  stat: path=/var/lib/mitgliederverwaltung/underlay/
  check_mode: no
  register: moinmoin_underlay_installed

- name: MoinMoin underlay-Verzeichnis von frischer MoinMoin Installation kopieren
  command: cp -r /usr/share/moin/underlay /var/lib/mitgliederverwaltung/ && chown -R www-data:www-data /var/lib/mitgliederverwaltung/underlay/
  when: moinmoin_underlay_installed.stat.isdir is not defined
#The following is not supported at the moment (remote recursive copy) therefore we have to copy it manually, see above.
#  copy: src=/usr/share/moin/underlay/
#        dest=/var/lib/mitgliederverwaltung/underlay/
#        remote_src=True

#- name: MoinMoin data-Verzeichnis grundauf neu generieren, wenn z.B. leeres MoinMoin getestet werden soll.
#  copy: src=/usr/share/moin/data
#        dst=/var/lib/mitgliederverwaltung/data
#        owner=www-data
#        group=www-data
#        mode=700

- name: Sind Daten für MoinMoin Installation bereits vorhanden?
  stat: path=/var/lib/mitgliederverwaltung/data/
  check_mode: no
  register: moinmoin_data_installed

- name: MoinMoin Macros kopieren
  copy: src=macro/
        dest=/var/lib/mitgliederverwaltung/data/plugin/macro/

- name: Backup der alten MoinMoin Installation zur neuen Installation kopieren
  fail:
    msg: TODO - Du musst das Backup des data/ Verzeichnisses per Hand selbst einspielen. Siehe auch roles/mitgliederverwaltung-server/info.txt
  when: moinmoin_data_installed.stat.isdir is not defined

- name: apt -- fail2ban Paket installieren
  apt:
          pkg: fail2ban
          state: present

- name: fail2ban apache Config kopieren
  copy: src=etc/fail2ban/
        dest=/etc/fail2ban/
  notify: restart fail2ban
