- name: restart munin-node
  service: name=munin-node state=restarted

- name: restart ssh
  service: name=ssh state=restarted

- name: restart ferm
  service: name=ferm state=restarted

- name: update-ca-certificates
  command: update-ca-certificates
