- name: install - Software installieren
  apt:
    name: buildbot-slave
    install_recommends: no
  register: buildslave_install

- name: install - Konfiguration erstellen
  command: "buildbot create-slave {{ opennetdev_slave_buildbot_path }}/{{ opennetdev_name }} {{ opennetdev_name }}.opennet-initiative.de {{ opennetdev_name }} {{ opennetdev_slave_buildbot_pass }}"
  args: 
    creates: "{{ opennetdev_slave_buildbot_path }}/{{ opennetdev_name }}/buildbot.tac"
  notify: restart buildslave

- name: install - Hostnamen setzen
  copy:
    content: "{{ opennetdev_slave_buildbot_host }}"
    dest: "{{ opennetdev_slave_buildbot_path }}/{{ opennetdev_name }}/info/host"
  notify:  restart buildslave

- name: install - Admin Kontakt setzen
  copy:
    content: "{{ opennetdev_slave_buildbot_admin }}"
    dest: "{{ opennetdev_slave_buildbot_path }}/{{ opennetdev_name }}/info/admin"
  notify:  restart buildslave

- name: install - Dienst aktivieren
  lineinfile:
    dest: "/etc/default/buildslave"
    backrefs: yes
    regexp: "SLAVE_ENABLED[1]"
    line: "SLAVE_ENABLED[1]=1"
  notify: restart buildslave
