- name: munin -- OpenVPN-Plugins fuer munin aktiveren
  copy: src=munin/{{ item }}
        dest=/etc/munin/plugins/
        mode=0755
  with_items:
    - openvpn_multiple
    - opennet_ugw_connections
    - opennet_user_connections_ping
    - opennet_user_connections_duration
  notify: restart munin-node

- name: munin -- OpenVPN-Plugins konfigurieren
  copy: src=munin/opennet_ugw.conf
        dest=/etc/munin/plugin-conf.d/opennet_ugw
  notify: restart munin-node

- name: munin -- OpenVPN-Tunnel aufzeichnen
  file: state=link
        src=/usr/share/munin/plugins/{{ item.source }}
        dest=/etc/munin/plugins/{{ item.target }}
  with_items:
    - { source: "if_", target: "if_{{ openvpn_users_interface }}" }
    - { source: "if_err_", target: "if_err_{{ openvpn_users_interface }}" }
    - { source: "if_", target: "if_{{ openvpn_ugw_interface }}" }
    - { source: "if_err_", target: "if_err_{{ openvpn_ugw_interface }}" }
  notify: restart munin-node
