- name: php installieren 
  apt: 
    name: php-cli

- name: vpnstatus - Verzeichnis anlegen
  file: 
    dest: "{{ openvpn_status_path }}"
    state: directory

- name: vpnstatus - Opennet Logo übertragen
  copy:
    src: Opennet_logo_quer.gif
    dest: "{{ openvpn_status_path }}"

- name: vpnstatus - PHP-Skript übertragen
  template: 
    src: "openvpn-status/{{ item }}"
    dest: "{{ openvpn_status_path }}/{{ item }}"
  with_items:
    - vpnstatus.php
    - openvpn_clients.php

- name: vpnstatus - Altes PHP-Skript entfernen
  file:
    dest: "{{ openvpn_status_path }}/index.php"
    state: absent

- name: vpnstatus - regelmäßig neu erstellen
  cron:
    name: "vpnstatus aktualisieren"
    job: "php {{openvpn_status_path }}/vpnstatus.php >{{ openvpn_status_path }}/index.html"
    minute: "*/3"
