- name: buildbot - Worker Software installieren
  apt:
    name: buildbot-worker
    install_recommends: no

- name: buildbot - Worker Dienst freischalten
  lineinfile:
    dest: "/etc/default/buildbot-worker"
    backrefs: yes
    regexp: "^WORKER_ENABLED"
    line: "WORKER_ENABLED[1]=1"
  notify: restart buildbot

- name: buildbot - Worker name setzen
  lineinfile:
    dest: "/etc/default/buildbot-worker"
    backrefs: yes
    regexp: "^WORKER_NAME"
    line: "WORKER_NAME[1]=\"{{ buildbot_worker_name }}\""
  notify: restart buildbot

- name: buildbot - Worker basedir setzen
  lineinfile:
    dest: "/etc/default/buildbot-worker"
    backrefs: yes
    regexp: "^WORKER_BASEDIR"
    line: "WORKER_BASEDIR[1]=\"{{ buildbot_worker_path }}\""
  notify: restart buildbot

- name: buildbot - Worker Autostart aktivieren
  systemd:
    name: "buildbot-worker@{{ buildbot_worker_name }}"
    enabled: yes
  notify: restart buildbot
