- name: upload - SSH Schlüssel erzeugen
  user:
    name: buildbot
    create_home: no
    home: "{{ buildbot_home }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_comment: "buildbot-{{ ansible_hostname }}"
    ssh_key_file: "{{ buildbot_home }}/.ssh/ssh_host_rsa_key"
  register: sshkey

- name: upload - copy new ssh key to download server
  fail:
    msg: New SSH key was created. This key needs to be added to downloads.on:/home/trac-bitten-slave/.ssh/authorized_keys manually. Rerun ansible after implementing this change.
  when: sshkey.changed

- name: upload - Test rsync connection to check ssh key is working
  command: "ssh -q -i /{{ buildbot_home }}/.ssh/ssh_host_rsa_key -o PasswordAuthentication=no {{ buildbot_upload_user }}@{{ buildbot_upload_host }} ls"
