- name: restart apache2
  service: name=apache2 state=restarted

- name: update mediawiki
  command: "php {{ mediawiki_path_lib }}/{{ mediawiki_script_maintainance }}"

- name: rebuild titlekeys
  command: "php {{ mediawiki_path_lib }}/{{ mediawiki_script_titlekeys }}"
