- name: ferm - Port öffnen
  template:
          src: ferm/350_apache2.inc
          dest: /etc/ferm/ferm.d/
  register: ferm_apache

# Ferm immer sofort neu laden, da später LE abhängig
- name: ferm - Dienst neu laden
  service: name=ferm state=reloaded
  when: ferm_apache.changed 
