- name: https - Letsencrypt Software vorhanden?
  stat:
         path=/usr/bin/dehydrated
  check_mode: no
  register: le_bin

- name: https - Letsencrypt Apache2 Konfigurationspaket installieren"
  apt: pkg=dehydrated-apache2 state=present
  when: le_bin.stat.exists

- name: https - Letsencrypt Zertifikate vorhanden?
  stat:
         path=/var/lib/dehydrated/certs
  check_mode: no
  register: le_cert
  when: le_bin.stat.exists

- name: https - Letsencrypt Cron Job ausführen 
  shell: /usr/bin/dehydrated --cron
  when: le_cert is defined and le_cert.stat.exists == false

- name: https - Apache SSL Modul aktivieren
  apache2_module:
         name=ssl
         state=present
  notify: restart apache2
  when: le_bin.stat.exists

#
# TODO: Mit Debian Buster erneut prüfen
# https://lists.debian.org/debian-devel-announce/2017/08/msg00004.html
# 
- name: https - Apache SSL Modul unsichere Protokolle deaktivieren
  lineinfile:
         path={{ apache2_https_conf }}
         regexp="SSLProtocol"
         line="	SSLProtocol all -SSLv3 -SSLv3 -TLSv1 -TLSv1.1"
  notify: restart apache2
  when: le_bin.stat.exists

- name: https - Apache SSL Modul sichere Cipher Reichenfolge aktivieren
  lineinfile:
         path={{ apache2_https_conf }}
         regexp="SSLHonorCipherOrder"
         line="	SSLHonorCipherOrder on"
  notify: restart apache2
  when: le_bin.stat.exists

- name: https - Apache SSL Modul strikte SNI Kontrolle aktivieren
  lineinfile:
         path={{ apache2_https_conf }}
         regexp="SSLStrictSNIVHostCheck"
         line="	SSLStrictSNIVHostCheck on"
  notify: restart apache2
  when: le_bin.stat.exists
