- include_tasks: apache.yml
- include_tasks: security.yml
- include_tasks: privacy.yml
- include_tasks: ferm.yml
- include_tasks: php.yml
- include_tasks: opennetca.yml
- include_tasks: sites.yml
- include_tasks: https.yml
- include_tasks: cleanup.yml
