- name: php - Apache Modul php7.0 deaktivieren
  apache2_module:
         name={{ apache2_php_version }}
         state=absent
  notify: restart apache2

- name: php - Apache Modul mpm_prefork deaktivieren
  apache2_module:
         name=mpm_prefork
         state=absent
         ignore_configcheck=yes

- name: php - Apache Modul mpm_event aktivieren
  apache2_module:
         name=mpm_event
         state=present
         ignore_configcheck=yes
  notify: restart apache2

- name: php - Apache Module f端r PHP installieren
  apt:   
         name="{{ packages }}"
  vars:
         packages:
         - libapache2-mod-fcgid
         - "{{ apache2_php_version }}-fpm"
  when: apache2_php

- name: php - Apache Module f端r PHP aktivieren
  apache2_module:
         name={{ item }}
         state=present
  with_items:
         - actions
         - fcgid
         - proxy_fcgi
         - alias
         - setenvif
  notify: restart apache2
  when: apache2_php

# TODO: warte auf Ansible Modul f端r a2enconf
- name: php - Apache Konfiguration f端r PHP aktivieren
  command: "a2enconf {{ apache2_php_version }}-fpm"
  register: conf_php
  changed_when: "'Enabling conf' in conf_php.stdout" 
  notify: restart apache2
  when: apache2_php
