- name: security - Apache2 Sicherheitskonfiguration kopieren
  template:
          src=security.conf
          dest="{{ apache2_conf_dir }}/security.conf"
          backup=yes
  notify: restart apache2

- name: security - Apache2 Opennet Sicherheitskonfiguration kopieren
  template:
          src=on-security.conf
          dest="{{ apache2_conf_dir }}/on-security.conf"
          backup=yes
  notify: restart apache2

# TODO: warte auf Ansible Modul für a2enconf
- name: security - Apache2 Opennet Sicherheitskonfiguration aktivieren
  command: "a2enconf on-security"
  register: conf_security
  changed_when: "'Enabling conf' in conf_security.stdout"
  notify: restart apache2
