- name: Gruppe anlegen
  group: state=present
         name={{ media_mirror_user }}
         system=yes

- name: Nutzer anlegen
  user:  state=present
         name={{ media_mirror_user }}
         group={{ media_mirror_user }}
         home={{ media_mirror_dir }}
         system=yes
         shell=/bin/false

- name: rsync installieren
  apt:   pkg=rsync state=present

- name: rsync Konfigurationsdatei übertragen
  template:
         src=rsyncd.conf
         dest=/etc/rsyncd.conf

- name: rsync (daemon mode) starten
  service:
        name=rsync
        state=started

- name: rsync Port via ferm öffnen
  template:
        src=ferm.conf
        dest=/etc/ferm/ferm.d/{{ media_mirror_ferm }}
  notify: restart ferm
