# TODO: remove mediawiki_extensions_wikimedia_old if all ext. moved to wfLoadExtension
- name: extensions - Installiere MediaWiki Erweiterungen
  git:
    repo: "https://gerrit.wikimedia.org/r/p/mediawiki/extensions/{{ item }}"
    dest: "{{ mediawiki_path_lib }}/extensions/{{ item }}"
    version: "{{ mediawiki_version }}"
    depth: 1
    force: yes
  with_items: 
  - "{{ mediawiki_extensions_wikimedia }}"
  - "{{ mediawiki_extensions_wikimedia_old }}"
  notify: update mediawiki

- name: extensions - Kopiere Konfigurationen für MediaWiki Erweiterungen
  copy:
    src: "extensions-conf.d"
    dest: "{{ mediawiki_path_conf }}"
    backup: yes
  notify: update mediawiki
