# TODO: auf python3 PyMySQL wechseln sobald es ohne Py-PIP arbeitet
- name: install - Mediawiki und weitere Werkzeuge installieren
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - mediawiki
    - automysqlbackup
    - imagemagick
#    - python3-pymysql
    - python-pymysql
  notify: restart apache2

# TODO: warte auf Ansible Modul für a2enconf
- name: install - Debian Apache Konfiguration für MediaWiki deaktivieren
  command: "a2disconf mediawiki"
  register: conf_mediawiki
  changed_when: "'Conf mediawiki disabled' in conf_mediawiki.stdout" 
  notify: restart apache2

- name: install - Opennet Logo kopieren
  copy: src="{{ mediawiki_logo }}" dest="{{ mediawiki_path }}/images"

- name: install - Debian alten mediawiki-extensions Pfad bereinigen
  file: path="/etc/mediawiki-extensions" state=absent
