- name: Mediawiki installieren
  apt: name=mediawiki state=present

- name: automysqlbackup installieren
  apt: name=automysqlbackup state=present

# TODO: warte auf Ansible Modul für a2enconf
- name: Debian Apache Konfiguration für MediaWiki deaktivieren
  command: "a2disconf mediawiki"
  register: conf_mediawiki
  changed_when: "'Conf mediawiki disabled' in conf_mediawiki.stdout" 
  notify: restart apache2
