- name: Mediawiki und weitere Werkzeuge installieren
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - mediawiki
    - automysqlbackup
    - imagemagick
  notify: restart apache2

# TODO: warte auf Ansible Modul für a2enconf
- name: Debian Apache Konfiguration für MediaWiki deaktivieren
  command: "a2disconf mediawiki"
  register: conf_mediawiki
  changed_when: "'Conf mediawiki disabled' in conf_mediawiki.stdout" 
  notify: restart apache2

#- name: Opennet Logo kopieren
#  copy: src=opennetlogo.png dest="{{ mediawiki_path }}/images"
