# TODO: auf python3 PyMySQL wechseln sobald es ohne Py-PIP arbeitet
- name: mediawiki - Mediawiki und weitere Werkzeuge installieren
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - mediawiki
    - automysqlbackup
    - imagemagick
#    - python3-pymysql
    - python-pymysql
  notify: restart apache2

# TODO: warte auf Ansible Modul für a2enconf
- name: mediawiki - Debian Apache Konfiguration für MediaWiki deaktivieren
  command: "a2disconf mediawiki"
  register: conf_mediawiki
  changed_when: "'Conf mediawiki disabled' in conf_mediawiki.stdout" 
  notify: restart apache2

- name: mediawiki - Opennet Logo kopieren
  copy: src=opennetlogo.png dest="{{ mediawiki_path }}/images"

- name: mediawiki - Einstellungen kopieren
  template:
    src: LocalSettings.php
    dest: "/etc/mediawiki/LocalSettings.php"
    backup: yes

- name: mediawiki - Vorlage für Passwortdatei kopieren
  template:
    src: LocalSettingsKeys.php
    dest: "/etc/mediawiki/LocalSettingsKeys.php"
    force: no
    backup: yes

- name: mediawiki - Opennet Einstellungen kopieren
  template:
    src: LocalSettingsOpennet.php
    dest: "/etc/mediawiki/LocalSettingsOpennet.php"
    backup: yes 
