- include_tasks: rsnapshot.yml

- include_tasks: encryption.yml
  when: backup_storage_crypto_device != ""

- name: öffentlichen ssh-Schlüssel des Backup-Sammlers abholen
  command: cat {{ backup_storage_ssh_public_key_path | quote }}
  register: backup_storage_ssh_public_key
  changed_when: False
  check_mode: False

# bereite alle zu sichernden Hosts vor
- include_tasks: source-hosts.yml
  with_items: "{{ backup_storage_source_hosts }}"
  loop_control:
    loop_var: "backup_source_host"

- include_tasks: monitoring.yml
