# in Jessie ist noch kein dehydrated-Paket enthalten
- name: "[dehydrated] jessie-backports-Repository hinzufügen"
  apt_repository:
          repo="deb http://ftp.debian.org/debian jessie-backports main"
          filename="jessie-backports"
          state=present
  when: ansible_distribution_release == "jessie"

- name: "[dehydrated] Installation"
  apt: pkg=dehydrated state=present

- name: "[cron] regelmäßige Erneuerung via cron"
  cron:
          name=dehydrated
          weekday=0
          hour=4
          minute=37
          state=present
          job="dehydrated --cron >/dev/null"

- name: "[dehydrated] renew-Hook konfigurieren"
  copy:
          src=dehydrated.conf
          dest=/etc/dehydrated/conf.d/local-hook.sh

- name: "[dehydrated] renew-Hook kopieren"
  copy:
          src=dehydrated-hook
          dest=/etc/dehydrated/hook.sh
          mode=755

- name: "[dehydrated] Domains festlegen"
  template:
          src=domains.txt
          dest=/etc/dehydrated/
  notify: update dehydrated-domains
