dns_zone_masters_ipv4:
  - 139.30.241.202
  - 192.168.10.2

dns_zone_masters_ipv6:
  - 2001:638:804:2228:5652:ff:fe41:6e19

dns_zone_master_with_dnskey: heartofgold.opennet-initiative.de

nameserver_secondary_ipv6: fd32:d8d3:87da::53
